default_settings: null
behaviors:    
  SpaceShooterAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2024
      buffer_size: 409600
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 42000000
    time_horizon: 2048
    summary_freq: 40000
    threaded: true
    
